INSERT INTO les.dbo.TIPOS_ENDERECO (tpe_nome, tpe_dt_cadastro, tpe_inativo)
VALUES ('Aeroporto', CURRENT_TIMESTAMP, 0),
 ('Alameda', CURRENT_TIMESTAMP, 0),
 ('Área', CURRENT_TIMESTAMP, 0),
 ('Avenida', CURRENT_TIMESTAMP, 0),
 ('Campo', CURRENT_TIMESTAMP, 0),
 ('Chácara', CURRENT_TIMESTAMP, 0),
 ('Colônia', CURRENT_TIMESTAMP, 0),
 ('Condomínio', CURRENT_TIMESTAMP, 0),
 ('Conjunto', CURRENT_TIMESTAMP, 0),
 ('Distrito', CURRENT_TIMESTAMP, 0),
 ('Esplanada', CURRENT_TIMESTAMP, 0),
 ('Estação', CURRENT_TIMESTAMP, 0),
 ('Estrada', CURRENT_TIMESTAMP, 0),
 ('Favela', CURRENT_TIMESTAMP, 0),
 ('Fazenda', CURRENT_TIMESTAMP, 0),
 ('Feira', CURRENT_TIMESTAMP, 0),
 ('Jardim', CURRENT_TIMESTAMP, 0),
 ('Ladeira', CURRENT_TIMESTAMP, 0),
 ('Lago', CURRENT_TIMESTAMP, 0),
 ('Lagoa', CURRENT_TIMESTAMP, 0),
 ('Largo', CURRENT_TIMESTAMP, 0),
 ('Loteamento', CURRENT_TIMESTAMP, 0),
 ('Morro', CURRENT_TIMESTAMP, 0),
 ('Núcleo', CURRENT_TIMESTAMP, 0),
 ('Parque', CURRENT_TIMESTAMP, 0),
 ('Passarela', CURRENT_TIMESTAMP, 0),
 ('Pátio', CURRENT_TIMESTAMP, 0),
 ('Praça', CURRENT_TIMESTAMP, 0),
 ('Quadra', CURRENT_TIMESTAMP, 0),
 ('Recanto', CURRENT_TIMESTAMP, 0),
 ('Residencial', CURRENT_TIMESTAMP, 0),
 ('Rodovia', CURRENT_TIMESTAMP, 0),
 ('Rua', CURRENT_TIMESTAMP, 0),
 ('Setor', CURRENT_TIMESTAMP, 0),
 ('Sítio', CURRENT_TIMESTAMP, 0),
 ('Travessa', CURRENT_TIMESTAMP, 0),
 ('Trecho', CURRENT_TIMESTAMP, 0),
 ('Vale', CURRENT_TIMESTAMP, 0),
 ('Vereda', CURRENT_TIMESTAMP, 0),
 ('Via', CURRENT_TIMESTAMP, 0),
 ('Viaduto', CURRENT_TIMESTAMP, 0),
 ('Viela', CURRENT_TIMESTAMP, 0),
 ('Via', CURRENT_TIMESTAMP, 0)

INSERT INTO les.dbo.TIPOS_TELEFONES(tpt_nome, tpt_dt_cadastro, tpt_inativo)
VALUES ('Celular', CURRENT_TIMESTAMP, 0),
('Residencial', CURRENT_TIMESTAMP, 0),
('Empresarial', CURRENT_TIMESTAMP, 0)

INSERT INTO les.dbo.BANDEIRAS_CARTAO_CREDITO(ban_nome, ban_dt_cadastro, ban_inativo)
VALUES ('Visa', CURRENT_TIMESTAMP, 0),
 ('Mastercard', CURRENT_TIMESTAMP, 0),
 ('American Express', CURRENT_TIMESTAMP, 0),
 ('Elo', CURRENT_TIMESTAMP, 0),
 ('Discover Network', CURRENT_TIMESTAMP, 0),
 ('Sodexo', CURRENT_TIMESTAMP, 0),
 ('Policard', CURRENT_TIMESTAMP, 0),
 ('Valecard', CURRENT_TIMESTAMP, 0),
 ('Agicard', CURRENT_TIMESTAMP, 0),
 ('JCB', CURRENT_TIMESTAMP, 0),
 ('CredSystem', CURRENT_TIMESTAMP, 0),
 ('Cabal', CURRENT_TIMESTAMP, 0),
 ('Greencard', CURRENT_TIMESTAMP, 0),
 ('Verocheque', CURRENT_TIMESTAMP, 0),
 ('Avista', CURRENT_TIMESTAMP, 0),
 ('Aura', CURRENT_TIMESTAMP, 0),
 ('Hipercard', CURRENT_TIMESTAMP, 0),
 ('Diners Club', CURRENT_TIMESTAMP, 0)

